name: DePloY
on:
  push:
    branches: main
    paths:
      - "src/**/*"
      - "**.ts"
      - "**.json"
      - "**.yml"
jobs:
  DePloY:
    runs-on: "ubuntu-latest"
    steps:
      - name: Deploying...
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.MAIN_HOST}}
          username: ${{ secrets.SSHUSERNAME }}
          password: ${{ secrets.SSHPASSWORD }}
          script: |
            cd /home/Discord-Bot
            git reset --hard
            git pull
            yarn
            yarn run compile
            pm2 reload /home/ecosystem.config.js --only Discord-Bot
