name: DePloY
on:
  push:
    branches: master
    paths:
      - "src/**/*"
      - "**.ts"
      - "**.json"
      - "**.yml"
jobs:
  DePloY:
    runs-on: "ubuntu-latest"
    steps:
      - name: Deploying...
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSHHOST }}
          username: ${{ secrets.SSHUSERNAME }}
          password: ${{ secrets.SSHPASSWORD }}
          script: |
            echo ${{ secrets.SSHPASSWORD }} >> p2.txt
            cd /home/PreMiD/Discord-Bot
            git reset --hard
            git pull
            yarn run compile
            pm2 restart 10
